### ISSUE TITLE
Create stun tower

### ISSUE THREAD

**Issue by carlos026** [carlos026/plantTD#16]
The turret will deal a fixed damage to the enemy and lock the enemy for 3 seconds.
We can user tower4 to stun the enemy.

**Comment by knando** [comment]
Test stats: costs 1500, damages for 2500, cooldown during 6s and stuns for 1,5s.

**Comment by carlos026** [comment]
This issue depends on the conclusion of https://github.com/carlos026/plantTD/issues/25 to be completed.

**Comment by knando** [comment]
Stun tower implemented and values updated. It does not follow exactly the original plan since we have upgrades now.
