### ISSUE TITLE
Sound effect - Turret

### ISSUE THREAD

**Issue by carlos026** [carlos026/plantTD#26]
Play a sound effect when the turret is firing.

In this case it's just the sound effect, there's no need to implement yet.

**Comment by carlos026** [comment]
This issue depends on the conclusion of https://github.com/carlos026/plantTD/issues/25 to be completed.

**Comment by bmattosrs** [comment]
Vi no Youtube que o sistema de foi adicionado. Muito bom.

**Comment by carlos026** [comment]
> Vi no Youtube que o sistema de foi adicionado. Muito bom.

Muito obrigado !
